generatorName: openapi
useSingleRequestParameter: false
supportAsync: false
preferUnsignedInt: true
basePathCustom: https://api.artifactsmmo.com
# operationIdNameMappings:
#   get_server_details__get: get_status
#   get_bank_details_my_bank_get: get_bank_details
#   get_bank_items_my_bank_items_get: get_bank_items
#   get_ge_orders_my_grandexchange_orders_get: get_ge_orders
#   get_ge_history_my_grandexchange_history_get: get_ge_history
#   get_account_details_my_details_get: get_account_details
#   change_password_my_change_password_post: change_password
#   get_pending_items_my_pending_items_get: get_pending_items
#   action_move_my__name__action_move_post: move_character
#   action_transition_my__name__action_transition_post: action_transition
#   action_rest_my__name__action_rest_post: rest_character
#   action_equip_item_my__name__action_equip_post: equip_item
#   action_unequip_item_my__name__action_unequip_post: unequip_item
#   action_use_item_my__name__action_use_post: use_item
#   action_fight_my__name__action_fight_post: fight
#   action_gathering_my__name__action_gathering_post: gather
#   action_crafting_my__name__action_crafting_post: craft
#   action_deposit_bank_gold_my__name__action_bank_deposit_gold_post: deposit_gold
#   action_deposit_bank_item_my__name__action_bank_deposit_item_post: deposit_item
#   action_withdraw_bank_item_my__name__action_bank_withdraw_item_post: withdraw_item
#   action_withdraw_bank_gold_my__name__action_bank_withdraw_gold_post: withdraw_gold
#   action_buy_bank_expansion_my__name__action_bank_buy_expansion_post: buy_bank_expansion
#   action_npc_buy_item_my__name__action_npc_buy_post: npc_buy_item
#   action_npc_sell_item_my__name__action_npc_sell_post: npc_sell_item
#   action_recycling_my__name__action_recycling_post: recycle
#   action_ge_buy_item_my__name__action_grandexchange_buy_post: ge_buy_item
#   action_ge_create_sell_order_my__name__action_grandexchange_create_sell_order_post: ge_create_sell_order
#   action_ge_cancel_order_my__name__action_grandexchange_cancel_post: ge_cancel_order
#   action_ge_create_buy_order_my__name__action_grandexchange_create_buy_order_post: ge_create_buy_order
#   action_ge_fill_my__name__action_grandexchange_fill_post: ge_fill_order
#   action_complete_task_my__name__action_task_complete_post: complete_task
#   action_task_exchange_my__name__action_task_exchange_post: task_exchange
#   action_accept_new_task_my__name__action_task_new_post: accept_new_task
#   action_task_trade_my__name__action_task_trade_post: task_trade
#   action_task_cancel_my__name__action_task_cancel_post: cancel_task
#   action_give_gold_my__name__action_give_gold_post: give_gold
#   action_give_items_my__name__action_give_item_post: give_items
#   action_claim_pending_item_my__name__action_claim_item__id__post: claim_pending_item
#   action_delete_item_my__name__action_delete_post: delete_item
#   action_change_skin_my__name__action_change_skin_post: change_skin
#   get_all_characters_logs_my_logs_get: get_all_characters_logs
#   get_character_logs_my_logs__name__get: get_character_logs
#   get_my_characters_my_characters_get: get_my_characters
#   create_account_accounts_create_post: create_account
#   forgot_password_accounts_forgot_password_post: forgot_password
#   reset_password_accounts_reset_password_post: reset_password
#   get_account_achievements_accounts__account__achievements_get: get_account_achievements
#   get_account_characters_accounts__account__characters_get: get_account_characters
#   get_account_accounts__account__get: get_account
#   get_all_achievements_achievements_get: get_all_achievements
#   get_achievement_achievements__code__get: get_achievement
#   get_all_badges_badges_get: get_all_badges
#   get_badge_badges__code__get: get_badge
#   create_character_characters_create_post: create_character
#   delete_character_characters_delete_post: delete_character
#   get_active_characters_characters_active_get: get_active_characters
#   get_character_characters__name__get: get_character
#   get_all_effects_effects_get: get_all_effects
#   get_effect_effects__code__get: get_effect
#   get_all_active_events_events_active_get: get_all_active_events
#   get_all_events_events_get: get_all_events
#   spawn_event_events_spawn_post: spawn_event
#   get_ge_history_grandexchange_history__code__get: get_ge_history
#   get_ge_orders_grandexchange_orders_get: get_ge_orders
#   get_ge_order_grandexchange_orders__id__get: get_ge_order
#   get_all_items_items_get: get_all_items
#   get_item_items__code__get: get_item
#   get_characters_leaderboard_leaderboard_characters_get: get_characters_leaderboard
#   get_accounts_leaderboard_leaderboard_accounts_get: get_accounts_leaderboard
#   get_all_maps_maps_get: get_all_maps
#   get_layer_maps_maps__layer__get: get_layer_maps
#   get_map_by_position_maps__layer___x___y__get: get_map_by_position
#   get_map_by_id_maps_id__map_id__get: get_map_by_id
#   get_all_monsters_monsters_get: get_all_monsters
#   get_monster_monsters__code__get: get_monster
#   get_all_npcs_npcs_details_get: get_all_npcs
#   get_npc_npcs_details__code__get: get_npc
#   get_npc_items_npcs_items__code__get: get_npc_items
#   get_all_npcs_items_npcs_items_get: get_all_npc_items
#   get_all_resources_resources_get: get_all_resources
#   get_resource_resources__code__get: get_resource
#   get_all_tasks_tasks_list_get: get_all_tasks
#   get_task_tasks_list__code__get: get_task
#   get_all_tasks_rewards_tasks_rewards_get: get_all_tasks_rewards
#   get_tasks_reward_tasks_rewards__code__get: get_tasks_reward
#   fight_simulation_simulation_fight_simulation_post: fight_simulation
#   generate_token_token_post: generate_token
